apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: application-team-admins
  namespace: {{ include "baseline.teamName" . }}
subjects:
  - kind: {{ .Values.access.iamPrincipalType }}
    apiGroup: rbac.authorization.k8s.io
    name: {{ .Values.access.ownerGroup | quote }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-administrators
subjects:
  - kind: {{ .Values.access.iamPrincipalType }}
    apiGroup: rbac.authorization.k8s.io
    name: {{ .Values.access.platformAdminGroup | quote }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-admin
