substitutions:
  _REGION: us-west1
  _REPOSITORY: gke-cluster-factory

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --pull
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/portal:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/portal:$COMMIT_SHA

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/portal:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
